### ISSUE TITLE
Wrong title

### ISSUE THREAD

**Issue by forflo** [lcpc2021/lcpc2021.github.io#1]
Hi,

thank you for writing the program.

https://github.com/lcpc2021/lcpc2021.github.io/blob/af12e2ccdcd6b04040a2546518e7ceb5065df1c1/program.html#L75

Could you instead use the following (non-blind) name of our publication.

`ORKA-HPC -- Practical ...`

Thank you & best regards,
Florian

**Comment by ghost** [comment]
Hi Florian,

Just updated.

Thanks,
Xiaoming

**Comment by forflo** [comment]
Thank you very much!
